"""add tags

Revision ID: eb31f745ef86
Revises: f27627e16644
Create Date: 2026-10-03 18:06:12.136915

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb31f745ef86"
down_revision: str | Sequence[str] | None = "f27627e16644"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("normalized_name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["assistant.users.uid"], name=op.f("fk_tags_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("owner_id", "normalized_name", name="uq_tag_owner_name"),
        schema="assistant",
    )
    op.create_index(
        op.f("ix_assistant_tags_owner_id"),
        "tags",
        ["owner_id"],
        unique=False,
        schema="assistant",
    )
    op.create_table(
        "note_tags",
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["assistant.notes.id"],
            name=op.f("fk_note_tags_note_id_notes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["assistant.tags.id"],
            name=op.f("fk_note_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("note_id", "tag_id", name=op.f("pk_note_tags")),
        schema="assistant",
    )
    op.create_index(
        "ix_note_tags_tag_id", "note_tags", ["tag_id"], unique=False, schema="assistant"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_note_tags_tag_id", table_name="note_tags", schema="assistant")
    op.drop_table("note_tags", schema="assistant")
    op.drop_index(
        op.f("ix_assistant_tags_owner_id"), table_name="tags", schema="assistant"
    )
    op.drop_table("tags", schema="assistant")
    # ### end Alembic commands ###
