"""baseline schema

Revision ID: f27627e16644
Revises:
Create Date: 2026-09-11 21:16:52.481650

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f27627e16644"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The `assistant` schema itself is created by alembic/env.py before this
    # (or any) migration runs, since alembic_version lives there too. This
    # extension is unrelated to that bootstrapping and just needs to exist
    # before any code (elsewhere) uses pgvector similarity search.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_query", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_sources")),
        schema="assistant",
    )
    op.create_table(
        "users",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("firstname", sa.String(length=255), nullable=False),
        sa.Column("lastname", sa.String(length=255), nullable=False),
        sa.Column("invite_quota_remaining", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="assistant",
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("credential_hash", sa.String(length=1024), nullable=True),
        sa.Column("provider_subject", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["assistant.users.uid"],
            name=op.f("fk_credentials_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_credential_provider_subject"
        ),
        sa.UniqueConstraint("user_id", "provider", name="uq_credential_user_provider"),
        schema="assistant",
    )
    op.create_table(
        "documents",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("creation_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_update_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["assistant.external_sources.id"],
            name=op.f("fk_documents_source_id_external_sources"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_documents")),
        schema="assistant",
    )
    op.create_table(
        "email_confirmations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resend_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["assistant.users.uid"],
            name=op.f("fk_email_confirmations_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_email_confirmations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_email_confirmations_token_hash")),
        schema="assistant",
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invitee_email", sa.String(length=255), nullable=False),
        sa.Column("inviter_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("quota_consumed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["assistant.users.uid"],
            name=op.f("fk_invites_inviter_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        schema="assistant",
    )
    op.create_index(
        op.f("ix_assistant_invites_invitee_email"),
        "invites",
        ["invitee_email"],
        unique=False,
        schema="assistant",
    )
    op.create_table(
        "notebooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["assistant.users.uid"],
            name=op.f("fk_notebooks_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notebooks")),
        sa.UniqueConstraint("name", name="uq_notebook_name"),
        schema="assistant",
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["assistant.users.uid"],
            name=op.f("fk_refresh_tokens_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
        schema="assistant",
    )
    op.create_index(
        "ix_refresh_tokens_token_hash",
        "refresh_tokens",
        ["token_hash"],
        unique=True,
        schema="assistant",
    )
    op.create_table(
        "document_metadata",
        sa.Column("document_uuid", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_uuid"],
            ["assistant.documents.uuid"],
            name=op.f("fk_document_metadata_document_uuid_documents"),
        ),
        sa.PrimaryKeyConstraint(
            "document_uuid", "key", name=op.f("pk_document_metadata")
        ),
        schema="assistant",
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notebook_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("creation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("update_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["notebook_id"],
            ["assistant.notebooks.id"],
            name=op.f("fk_notes_notebook_id_notebooks"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["assistant.users.uid"], name=op.f("fk_notes_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
        sa.UniqueConstraint(
            "notebook_id", "external_id", name="uq_note_notebook_external_id"
        ),
        schema="assistant",
    )
    op.create_table(
        "entitlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("note_id", sa.UUID(), nullable=True),
        sa.Column("notebook_id", sa.UUID(), nullable=True),
        sa.Column("permission_name", sa.String(length=30), nullable=True),
        sa.Column("role_name", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(note_id IS NOT NULL AND notebook_id IS NULL) OR (note_id IS NULL AND notebook_id IS NOT NULL)",
            name=op.f("ck_entitlements_ck_entitlement_one_subject"),
        ),
        sa.CheckConstraint(
            "(permission_name IS NOT NULL AND role_name IS NULL) OR (permission_name IS NULL AND role_name IS NOT NULL)",
            name=op.f("ck_entitlements_ck_entitlement_one_grant"),
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["assistant.notes.id"],
            name=op.f("fk_entitlements_note_id_notes"),
        ),
        sa.ForeignKeyConstraint(
            ["notebook_id"],
            ["assistant.notebooks.id"],
            name=op.f("fk_entitlements_notebook_id_notebooks"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["assistant.users.uid"],
            name=op.f("fk_entitlements_principal_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlements")),
        sa.UniqueConstraint(
            "principal_id",
            "note_id",
            "notebook_id",
            "permission_name",
            "role_name",
            name="uq_entitlement_no_duplicate_grant",
        ),
        schema="assistant",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=1024), nullable=False),
        sa.Column("creation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"], ["assistant.notes.id"], name=op.f("fk_files_note_id_notes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        schema="assistant",
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("part_number", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=1024), nullable=False),
        sa.Column("creation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["assistant.files.id"], name=op.f("fk_chunks_file_id_files")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        schema="assistant",
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("node_type", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("block_type", sa.String(length=20), nullable=True),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("update_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(node_type = 'text' AND payload IS NOT NULL AND attachment_id IS NULL AND block_type IS NULL) OR (node_type = 'attachment' AND payload IS NOT NULL AND attachment_id IS NOT NULL AND block_type IS NULL) OR (node_type = 'markdown' AND payload IS NOT NULL AND attachment_id IS NULL AND block_type IS NOT NULL)",
            name=op.f("ck_nodes_ck_node_type_fields"),
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["assistant.files.id"],
            name=op.f("fk_nodes_attachment_id_files"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["assistant.users.uid"], name=op.f("fk_nodes_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["assistant.notes.id"], name=op.f("fk_nodes_note_id_notes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        schema="assistant",
    )
    op.create_index(
        "ix_nodes_note_id_position",
        "nodes",
        ["note_id", "position"],
        unique=False,
        schema="assistant",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nodes_note_id_position", table_name="nodes", schema="assistant")
    op.drop_table("nodes", schema="assistant")
    op.drop_table("chunks", schema="assistant")
    op.drop_table("files", schema="assistant")
    op.drop_table("entitlements", schema="assistant")
    op.drop_table("notes", schema="assistant")
    op.drop_table("document_metadata", schema="assistant")
    op.drop_index(
        "ix_refresh_tokens_token_hash", table_name="refresh_tokens", schema="assistant"
    )
    op.drop_table("refresh_tokens", schema="assistant")
    op.drop_table("notebooks", schema="assistant")
    op.drop_index(
        op.f("ix_assistant_invites_invitee_email"),
        table_name="invites",
        schema="assistant",
    )
    op.drop_table("invites", schema="assistant")
    op.drop_table("email_confirmations", schema="assistant")
    op.drop_table("documents", schema="assistant")
    op.drop_table("credentials", schema="assistant")
    op.drop_table("users", schema="assistant")
    op.drop_table("external_sources", schema="assistant")
    # ### end Alembic commands ###
