"""Fractional indexing for node position ordering.

Positions are short lexicographically sortable strings. Between any
two positions a new one can always be generated by extending the
string. The alphabet is ``0-9A-Za-z`` (62 characters).
"""

from __future__ import annotations

ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
BASE = len(ALPHABET)
_CHAR_TO_INDEX = {c: i for i, c in enumerate(ALPHABET)}
_MID = BASE // 2


def _index(c: str) -> int:
    return _CHAR_TO_INDEX[c]


def _midpoint_integers(a: list[int], b: list[int]) -> list[int]:
    """Compute the midpoint between two base-62 digit lists.

    Both lists are aligned to the same length (right-padded with 0).
    If the midpoint equals *a*, a new digit at the midpoint of the
    remaining range is appended.
    """
    max_len = max(len(a), len(b))
    a = a + [0] * (max_len - len(a))
    b = b + [0] * (max_len - len(b))

    # Convert to a single integer in base BASE, find midpoint,
    # convert back.
    val_a = 0
    val_b = 0
    for i in range(max_len):
        val_a = val_a * BASE + a[i]
        val_b = val_b * BASE + b[i]

    if val_b <= val_a:
        msg = "before must be less than after"
        raise ValueError(msg)

    mid_val = (val_a + val_b) // 2

    if mid_val == val_a:
        # Gap too small at this precision — extend by one digit.
        # Pick midpoint between a's extended digit (0) and BASE.
        result_digits: list[int] = []
        tmp = mid_val
        for _ in range(max_len):
            result_digits.append(tmp % BASE)
            tmp //= BASE
        result_digits.reverse()
        result_digits.append(_MID)
        return result_digits

    result: list[int] = []
    tmp = mid_val
    for _ in range(max_len):
        result.append(tmp % BASE)
        tmp //= BASE
    result.reverse()

    # Strip trailing zeros for shorter keys.
    while len(result) > 1 and result[-1] == 0:
        result.pop()

    return result


def _to_digits(s: str) -> list[int]:
    return [_index(c) for c in s]


def _from_digits(digits: list[int]) -> str:
    return "".join(ALPHABET[d] for d in digits)


def generate_position_between(
    before: str | None,
    after: str | None,
) -> str:
    """Generate a position string between *before* and *after*.

    Args:
        before: The preceding position, or ``None`` for the start.
        after: The following position, or ``None`` for the end.

    Returns:
        A new position that sorts between the two bounds.

    Raises:
        ValueError: If *before* >= *after* when both are given.
    """
    if before is not None and after is not None:
        if before >= after:
            msg = f"before ({before!r}) must be less than " f"after ({after!r})"
            raise ValueError(msg)
        a = _to_digits(before)
        b = _to_digits(after)
        return _from_digits(_midpoint_integers(a, b))

    if before is None and after is None:
        return generate_first_position()

    if before is None:
        # Generate a position before *after*.
        after_digits = _to_digits(after)  # type: ignore[arg-type]
        # Try halving the value.
        zero = [0] * len(after_digits)
        return _from_digits(_midpoint_integers(zero, after_digits))

    # after is None — generate a position after *before*.
    return before + ALPHABET[_MID]


def generate_first_position() -> str:
    """Return the initial position for an empty list."""
    return ALPHABET[_MID]


def generate_n_positions(
    n: int,
    after: str | None = None,
) -> list[str]:
    """Generate *n* successive positions after *after*.

    Args:
        n: Number of positions to generate.
        after: Starting position (``None`` for the beginning).

    Returns:
        A sorted list of *n* new position strings.
    """
    positions: list[str] = []
    prev = after
    for _ in range(n):
        pos = generate_position_between(prev, None)
        positions.append(pos)
        prev = pos
    return positions
