"""SQLAlchemy database models."""

from __future__ import annotations

import uuid as uuid_module
from datetime import datetime  # noqa: TC003
from enum import Enum

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from assistant.models.database import Base


class DocumentFormat(str, Enum):
    """Document format enumeration."""

    TEXT = "text"
    MARKDOWN = "markdown"
    PDF = "pdf"


class Document(Base):
    """Document model representing a document from an external source.

    Attributes:
        uuid: Primary key UUID generated by the system.
        external_id: ID of the document in the external source.
        creation_datetime: When the document was created in the external source.
        last_update_datetime: When the document was last updated in the external source.
        title: Title of the document from the external source.
        format: Format of the document (text, markdown, or PDF).
        source_id: Foreign key to the ExternalSource.
        source: Relationship to the ExternalSource.
    """

    __tablename__ = "documents"
    __table_args__ = {"schema": "assistant"}  # noqa: RUF012

    uuid: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid_module.uuid4,
        nullable=False,
    )
    external_id: Mapped[str] = mapped_column(String(255), nullable=False)
    creation_datetime: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    last_update_datetime: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    format: Mapped[DocumentFormat] = mapped_column(
        String(20),
        nullable=False,
    )
    source_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("external_sources.id"),
        nullable=False,
    )

    # Relationships
    source: Mapped[ExternalSource] = relationship(
        "ExternalSource",
        back_populates="documents",
    )


class ExternalSource(Base):
    """External source model representing a configured external source.

    Attributes:
        id: Primary key UUID.
        provider: Provider identifier (e.g., "evernote", "fake").
        provider_query: Source-specific query parameters as JSON string.
        documents: Relationship to documents from this source.
    """

    __tablename__ = "external_sources"
    __table_args__ = {"schema": "assistant"}  # noqa: RUF012

    id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid_module.uuid4,
    )
    provider: Mapped[str] = mapped_column(String(100), nullable=False)
    provider_query: Mapped[str] = mapped_column(Text, nullable=True)

    # Relationships
    documents: Mapped[list[Document]] = relationship(
        "Document",
        back_populates="source",
        cascade="all, delete-orphan",
    )
